// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 9.11 and Filter Design HDL Coder 3.1.10.
// Generated on: 2022-12-12 18:50:36
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// AddPipelineRegisters: on
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure        : Cascaded Integrator-Comb Decimator
// Decimation Factor       : 16
// Differential Delay      : 1
// Number of Sections      : 1
// Stable                  : Yes
// Linear Phase            : Yes (Type 2)
//
// Input                   : s14,0
// Output                  : s14,-4
// Filter Internals        : Specified Word Lengths
//   Integrator Section 1  : s20,2
//   Comb Section 1        : s20,2
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module CIC_R16_N1_DEC
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [13:0] filter_in; //sfix14
  output  signed [13:0] filter_out; //sfix14_E4
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  // Signals
  reg  [3:0] cur_count; // ufix4
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  //   
  reg  signed [13:0] input_register; // sfix14
  //   -- Section 1 Signals 
  wire signed [13:0] section_in1; // sfix14
  wire signed [19:0] section_cast1; // sfix20_En2
  wire signed [19:0] sum1; // sfix20_En2
  reg  signed [19:0] section_out1; // sfix20_En2
  wire signed [19:0] add_cast; // sfix20_En2
  wire signed [19:0] add_cast_1; // sfix20_En2
  wire signed [20:0] add_temp; // sfix21_En2
  //   -- Section 2 Signals 
  wire signed [19:0] section_in2; // sfix20_En2
  reg  signed [19:0] diff1; // sfix20_En2
  wire signed [19:0] section_out2; // sfix20_En2
  wire signed [19:0] sub_cast; // sfix20_En2
  wire signed [19:0] sub_cast_1; // sfix20_En2
  wire signed [20:0] sub_temp; // sfix21_En2
  wire signed [13:0] output_typeconvert; // sfix14_E4
  //   
  reg  signed [13:0] output_register; // sfix14_E4

  // Block Statements
  //   ------------------ CE Output Generation ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 4'b0000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 4'b1111) begin
            cur_count <= 4'b0000;
          end
          else begin
            cur_count <= cur_count + 4'b0001;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 4'b0001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  //   ------------------ Input Register ------------------

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  //   ------------------ Section # 1 : Integrator ------------------

  assign section_in1 = input_register;

  assign section_cast1 = $signed({section_in1[13:0], 2'b00});

  assign add_cast = section_cast1;
  assign add_cast_1 = section_out1;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[19:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section1
      if (reset == 1'b1) begin
        section_out1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out1 <= sum1;
        end
      end
    end // integrator_delay_section1

  //   ------------------ Section # 2 : Comb ------------------

  assign section_in2 = section_out1;

  assign sub_cast = section_in2;
  assign sub_cast_1 = diff1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign section_out2 = sub_temp[19:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section2
      if (reset == 1'b1) begin
        diff1 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff1 <= section_in2;
        end
      end
    end // comb_delay_section2

  assign output_typeconvert = section_out2[19:6];

  //   ------------------ Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: output_reg_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_reg_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // filter
